//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace serwis_console {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Questions {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Questions() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("serwis_console.Questions", typeof(Questions).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Czy Komputer stacjonarny?.
        /// </summary>
        internal static string IsDefaultPC {
            get {
                return ResourceManager.GetString("IsDefaultPC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Czy drukarka atramentowa?.
        /// </summary>
        internal static string IsDefaultPrinter {
            get {
                return ResourceManager.GetString("IsDefaultPrinter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wymień baterię.
        /// </summary>
        internal static string L_N1 {
            get {
                return ResourceManager.GetString("L_N1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wymień matrycę.
        /// </summary>
        internal static string L_N2 {
            get {
                return ResourceManager.GetString("L_N2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Czy test pamięci ram prawidłowy?.
        /// </summary>
        internal static string L_N3 {
            get {
                return ResourceManager.GetString("L_N3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wymień pamiec RAM.
        /// </summary>
        internal static string L_N4 {
            get {
                return ResourceManager.GetString("L_N4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zmień dysk i odtwórz system z dysku odzyskiwania.
        /// </summary>
        internal static string L_N5 {
            get {
                return ResourceManager.GetString("L_N5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Czy mozna właczyc tryb awaryjny?.
        /// </summary>
        internal static string L_N6 {
            get {
                return ResourceManager.GetString("L_N6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zainstaluj system operacyjny z kopii zapasowej.
        /// </summary>
        internal static string L_N7 {
            get {
                return ResourceManager.GetString("L_N7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Czy mozna włączyć.
        /// </summary>
        internal static string L_T1 {
            get {
                return ResourceManager.GetString("L_T1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Czy widać obraz?.
        /// </summary>
        internal static string L_T2 {
            get {
                return ResourceManager.GetString("L_T2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Czy przeszedł test POST?.
        /// </summary>
        internal static string L_T3 {
            get {
                return ResourceManager.GetString("L_T3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Czy test dysku prawidłowy?.
        /// </summary>
        internal static string L_T4 {
            get {
                return ResourceManager.GetString("L_T4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sprawdz poziom napiecia na plycie glownej.
        /// </summary>
        internal static string L_T5 {
            get {
                return ResourceManager.GetString("L_T5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Czy system operacyjny sie ładuje prawidłowo?.
        /// </summary>
        internal static string L_T6 {
            get {
                return ResourceManager.GetString("L_T6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Czy system wykazuje błedy?.
        /// </summary>
        internal static string L_T7 {
            get {
                return ResourceManager.GetString("L_T7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wprowadz progam naprawczy zgodnie z spisem błędów.
        /// </summary>
        internal static string L_T8 {
            get {
                return ResourceManager.GetString("L_T8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Włacz odzyskiwanie systemu.
        /// </summary>
        internal static string L_T9 {
            get {
                return ResourceManager.GetString("L_T9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wymień kabel zasilający oraz zasilacz..
        /// </summary>
        internal static string N0 {
            get {
                return ResourceManager.GetString("N0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Czy głowica w karetce?.
        /// </summary>
        internal static string N1 {
            get {
                return ResourceManager.GetString("N1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Czy istnieje osobny bęben?.
        /// </summary>
        internal static string N10 {
            get {
                return ResourceManager.GetString("N10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Czy toner jest pusty?.
        /// </summary>
        internal static string N11 {
            get {
                return ResourceManager.GetString("N11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Czy drukarka zostawia slady tonera?.
        /// </summary>
        internal static string N12 {
            get {
                return ResourceManager.GetString("N12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Czy wydruk się rozmazuje?.
        /// </summary>
        internal static string N13 {
            get {
                return ResourceManager.GetString("N13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Przejrzyj i oczyść całą sciezke druku.
        /// </summary>
        internal static string N14 {
            get {
                return ResourceManager.GetString("N14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Czy tusze puste?.
        /// </summary>
        internal static string N2 {
            get {
                return ResourceManager.GetString("N2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wykonaj kalibrację drukarki programowo.
        /// </summary>
        internal static string N3 {
            get {
                return ResourceManager.GetString("N3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dokonaj restartu licznika głowicy programowo.
        /// </summary>
        internal static string N4 {
            get {
                return ResourceManager.GetString("N4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Czy drukarka laserowa?.
        /// </summary>
        internal static string N5 {
            get {
                return ResourceManager.GetString("N5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Czy drukarka 3d?.
        /// </summary>
        internal static string N6 {
            get {
                return ResourceManager.GetString("N6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Czy drukarka igłowa?.
        /// </summary>
        internal static string N7 {
            get {
                return ResourceManager.GetString("N7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Czy drukarka kolorowa?.
        /// </summary>
        internal static string N8 {
            get {
                return ResourceManager.GetString("N8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Czy posiada toner z bębnem?.
        /// </summary>
        internal static string N9 {
            get {
                return ResourceManager.GetString("N9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chwilowy brak wsparcia - odeślij klienta do innego serwisu.
        /// </summary>
        internal static string NoSupprt {
            get {
                return ResourceManager.GetString("NoSupprt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Czy prąd jest dostarczony?.
        /// </summary>
        internal static string PC_N1 {
            get {
                return ResourceManager.GetString("PC_N1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zmień kabel zasilający.
        /// </summary>
        internal static string PC_N2 {
            get {
                return ResourceManager.GetString("PC_N2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Czy komputer wydaje dzwięki/piski?.
        /// </summary>
        internal static string PC_N3 {
            get {
                return ResourceManager.GetString("PC_N3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sprawdz szynę zasilajaca płyty głównej.
        /// </summary>
        internal static string PC_N4 {
            get {
                return ResourceManager.GetString("PC_N4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Włacz odzyskiwanie systemu.
        /// </summary>
        internal static string PC_N5 {
            get {
                return ResourceManager.GetString("PC_N5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Włacz test i naprawianie systemu.
        /// </summary>
        internal static string PC_N6 {
            get {
                return ResourceManager.GetString("PC_N6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Czy mozna włączyć.
        /// </summary>
        internal static string PC_T1 {
            get {
                return ResourceManager.GetString("PC_T1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wymień zasilacz.
        /// </summary>
        internal static string PC_T2 {
            get {
                return ResourceManager.GetString("PC_T2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Czy załacza się bios i POST?.
        /// </summary>
        internal static string PC_T3 {
            get {
                return ResourceManager.GetString("PC_T3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zdiagnozuj problem zgodnie z rodzajem dzwięku według dokumentacji.
        /// </summary>
        internal static string PC_T4 {
            get {
                return ResourceManager.GetString("PC_T4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Czy system operacyjny się ładuje prawidłowo?.
        /// </summary>
        internal static string PC_T5 {
            get {
                return ResourceManager.GetString("PC_T5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Czy system loguje błedy.
        /// </summary>
        internal static string PC_T6 {
            get {
                return ResourceManager.GetString("PC_T6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Napraw sterownik/bibliotekę/uprawnienie zgodnie z logiem..
        /// </summary>
        internal static string PC_T7 {
            get {
                return ResourceManager.GetString("PC_T7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wybrana została diagnoza drukarki.
        /// </summary>
        internal static string Printer {
            get {
                return ResourceManager.GetString("Printer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Czy drukarka się świeci/włacza?.
        /// </summary>
        internal static string T1 {
            get {
                return ResourceManager.GetString("T1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wymień.
        /// </summary>
        internal static string T11 {
            get {
                return ResourceManager.GetString("T11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sprawdz transfer i rolki sciezki druku..
        /// </summary>
        internal static string T12 {
            get {
                return ResourceManager.GetString("T12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sprawdz Fuser i rolkę dociskającą papier..
        /// </summary>
        internal static string T13 {
            get {
                return ResourceManager.GetString("T13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Czy drukarka drukuje?.
        /// </summary>
        internal static string T2 {
            get {
                return ResourceManager.GetString("T2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Czy głowica zaschnięta?.
        /// </summary>
        internal static string T3 {
            get {
                return ResourceManager.GetString("T3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dokonaj oczyszczenia chemicznego głowicy.
        /// </summary>
        internal static string T4 {
            get {
                return ResourceManager.GetString("T4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wymień na nowe tusze.
        /// </summary>
        internal static string T5 {
            get {
                return ResourceManager.GetString("T5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Czy mozna włączyć drukarkę?.
        /// </summary>
        internal static string T6 {
            get {
                return ResourceManager.GetString("T6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Czy drukarka zgłasza zacięcie papieru?.
        /// </summary>
        internal static string T7 {
            get {
                return ResourceManager.GetString("T7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuń zacięcie zgodnie z informacją drukarki.
        /// </summary>
        internal static string T8 {
            get {
                return ResourceManager.GetString("T8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Czy drukarka zgłasza błędy?.
        /// </summary>
        internal static string T9 {
            get {
                return ResourceManager.GetString("T9", resourceCulture);
            }
        }
    }
}
